# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fd327f01bd38a734f14c6fb04bffe58b26fcb76c8a85243bf83429840a5506501cfcee23dd121bb8782e567eaff7ac61d780b9c2d7fb9c7ef5a896b76c8d490

test:
  secret_key_base: 2ad01d35e65b10c0d4a128920d1a55f6283028bd7eb3221a1036e78524a72a7df3e3b7b37ee3ee993cdeabe4aced0b1e0a1e125cd09a3934e6dfc5f79e15af3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
